### ISSUE TITLE
State management

### ISSUE THREAD

**Issue by karneaud** [udamir/magx#4]
I'm looking at your state management logic. Based on what I'm seeing can I assume the following is how it works:-

1.  Create the state object
2. Create a tracker with Serializer
3. Use onSnapshot client side to update/ retrieve state?

But I have the following questions

- Is it that the "patch tracker" are instantiated on game connection ?
- Is the tracker listeners created on instantiation ?

Also 

- do I "need" to use MosX state management? 
- If I use my own...do I need to serialize it using the serializer?
- Do I also need to follow the same patterns for my state management?

Examples would be appreciated. Thanks in advance.

**Comment by udamir** [comment]
The main idea that I tried to implement in Magx is automatic synchronization of state between server and clients. The principle is as follows - when client connected receives a full snapshot, and after receives all the changes in JsonPatch format. Unlike the Colyseus, [mosx](https://udamir.github.io/mosx/) supports private objects in state and computed properties.

Regarding your questions:
1. Tracker is instantiated on [room creation](https://github.com/udamir/magx/blob/779cb64966a4d0dd45ae268713e541cada3e8f45/packages/core/src/rooms.ts#L299). Tracker must be created in `createPatchTracker` method
2. Connected clients start [listen for changes](https://github.com/udamir/magx/blob/779cb64966a4d0dd45ae268713e541cada3e8f45/packages/core/src/rooms.ts#L78) 

You have the freedom and flexibility to choose state management engine without limitations, but you need to implement  change tracking functionality via JsonPatch (https://github.com/udamir/magx/blob/master/packages/core/src/room/tracker.ts) for example via mobx. By the way Mosx is based on mobx v5.

Magx uses MessagePack for serialization, but you can use any implementation. You can use PatchPack library for [JsonPatch](https://github.com/udamir/patchpack) serialization.

You can find examples of Magx with mosx and without in [example project](https://github.com/udamir/magx/tree/master/examples)
