### ISSUE TITLE
Multiple State Objects

### ISSUE THREAD

**Issue by karneaud** [udamir/magx#5]
I see in your code you create and serial a state. Can you patch track multiple states?

e.g.

```
createStates () => { Player, House }

createPatchTracker(state: State) {
    // create state change tracker
    return Mosx.createTracker(state, { serializer: SchemaSerializer })
...
```

or do I need to manage the house state from within the player

```
class PlayerState {
 this.player  = new Player
this.house = new House

}
```

**Comment by udamir** [comment]
No. One state for one room.  Each player's state is part of room state:
 ```ts
 @mx.Object
export class Player {
  @mx public x
  @mx public y
}

@mx.Object
export class House {
// ...
}

@mx.Object
export class State {
  @mx public players = new Map<string, Player>()
  @mx public house = new House()
}
```
Check out [example](https://github.com/udamir/magx/blob/master/examples/src/rooms/basic/mosx-state.ts) project to get working sample. Also documentation for Mosx State management is available https://udamir.github.io/mosx/

**Comment by karneaud** [comment]
Thanks...already making the adjustments.
