### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by karneaud** [udamir/magx#6]
So I'm using the latest magx with the following setup

```
 gameServer = new Server(server),
gameServer.define('pullowar', PullOWarRoom);
server.listen(port, () => console.log(`Listening on http://localhost:${ port }`));
```

the PullOWarRoom 

```
class PullOWarRoom extends Room {
  constructor(options) {
   this.maxClients = options.maxClients || 2;
  }

   createState(){
    // create state
    return new State()
  }

  createPatchTracker(state) {
    // create state change tracker
    return mosx.Mosx.createTracker(state, { serializer: mosx.SchemaSerializer })
  }

   onCreate(params ) {
   	console.log('on create', params)
  }


  onLeave() {
  	this.state.removePlayer();
  	this.state.resetGame();
  }

  onJoin() {
    if( this.state.game.players == this.maxClients && this.state.game.state === false )
    {
      this.state.setGameState( GAME_READY)
      this.state.startNextRound()
    } else {
      this.state.addPlayer()
    }
  }

  onClose() {
    delete this.state
  }
}

```

And I connect to the server using

```
// http://localhost:2567/magx"
client.authenticate().then((d) => {
                               	console.log(d)
                               return (ROOM_ID ? client.joinRoom(ROOM_ID) : client.createRoom('pullowar'))
    }).then(room => {
    	.....
```

I'm not sure how auth works but the but i get a "timeout" trying to connect via "http://localhost:2567/magx/auth"

I'm also using the magx-monitor but in accessing the url "http://localhost:2567/magx/monitor" the page loads but I get the error

> net::ERR_SSL_PROTOCOL_ERROR
> monitor:61 Uncaught ReferenceError: MagX is not defined
    at monitor:61

I'm assuming the first error is due to not setting up auth? Can I disable auth at least on localhost?
The second maybe due to not using https? Can I also disable this at least on localhost?

**Comment by udamir** [comment]
Hi, please clone this [example](https://github.com/udamir/magx-examples) project and try to add your custom room base on the provided examples.

Regarding your errors:
1. `MagX is not defined` - add dependency `magx-client` to your project to make '/magx' path available
2. Use `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` in your html header to upgrade your connection to https.
3. By default guest authentication is used, so if you don't add your custom logic, it will work for all clients.

**Comment by karneaud** [comment]
@udamir while I'd like to clone your examples they are written in TS which i'm not too familiar with. I also don't think your examples are working properly (I tried to view them at https://magx-examples.vercel.app/basic/lobby.html) and it did not work.

**Comment by karneaud** [comment]
Ok . I solved this issue by enabling cors and https. The monitor interface shows up
