### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by karneaud** [udamir/magx#7]
So I'm using cors and https to run the server( port 2567) while I run the game on a different server( port 3000).

While the logs show I'm able to create a room

> Process 70: Get avalible rooms 
> Find process for room: 
> Current process load: {} 
> All cluster pids [] 
> Process 70 requested: Create room pullowar

The client side seems to return a 

> Request URL: https://localhost:2567/magx/rooms
> Request Method: POST
> Status Code: 400 Bad Request
> Remote Address: [2803:1500:e00:f22f:ba27:ebff:fede:91d0]:2567
> Referrer Policy: strict-origin-when-cross-origin

with the following payload.

> {"name":"pullowar","options":{}}

Did I need to set additional options for the room to be initialized?

**Comment by karneaud** [comment]
I notice that the authentication returns a token. Was I suppose to use the token when trying to create to join the room?

**Comment by udamir** [comment]
token is required for this API method. All available methods in [api.ts](https://github.com/udamir/magx/blob/master/packages/core/src/api.ts) file. 
I assume you are getting 400 error because the room with that name is not defined

The easiest way to start using magx server is via [magx-client](https://github.com/udamir/magx/tree/master/packages/magx-client) library, or you will have to implement all connection/communication logic yourself

**Comment by karneaud** [comment]
@udamir 

Well based on your example I seem to be instantiating it correctly. Only difference is I had to use "https" in order for the monitor to work.

```
const createServer = require('https').createServer,
      fs = require('fs'),
  production = process.env.NODE_ENV || false,
  port = process.env.PORT || 2567,
  Server = require('magx').Server,
  server = createServer({
  	key: fs.readFileSync(__dirname + '/../private.key'),
  	cert: fs.readFileSync(__dirname + '/../private.crt')
  }),
  gameServer = new Server(server),
  PullOWarRoom = require('./rooms'),
      monitor = require('magx-monitor').monitor;

gameServer.define('pullowar', PullOWarRoom);
.....
```


and I am using the client correctly. Do I need to set the token manually? As I see it being passed in the headers.

```
client.authenticate().then((r) => {
    console.log('auth', r)
    return client.getRooms()
    }).then((rooms) => {
    console.log('rooms', rooms); // does 
                                          return                       (ROOM_ID ? client.joinRoom(ROOM_ID) : client.createRoom('pullowar'))
    } ).then(room => {
    	Room = room;
  		setGameId( room.id)
 ...

}).catch(e => {
  		console.log("JOIN ERROR", e); // prints 400 bad request 
	})
``` 		

The game says its creating the room

> Process 70: Get avalible rooms 
> Find process for room: 
> Current process load: {} 
> All cluster pids [] 
> Process 70 requested: Create room pullowar
 
However the monitor does not list it.

If I don't use CORs or HTTPS I get the other previous issues I logged in repo.

**Comment by udamir** [comment]
you need to call `monitor(gameServer)` to attach monitor to magx server. 
Monitor is very poor module, but it works with http as well as with https.

I tested magx server with https also, and did't have any issues.

**Comment by udamir** [comment]
If client don't join the room after creation it is closing automatically.
